import React, { useState } from "react"; 
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/globals.module.css";

export default function Home() {
  const [nome, setNome] = useState("");
  const [email, setEmail] = useState("");
  const [clientes, setClientes] = useState<{ nome: string; email: string }[]>([]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!nome || !email) {
      alert("Preencha todos os campos!");
      return;
    }

    setClientes([...clientes, { nome, email }]);
    setNome("");
    setEmail("");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.page}>
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js logo"
            width={180}
            height={38}
            priority
          />

          <h1>Cadastro de Clientes</h1>

          {/* Formulário */}
          <form onSubmit={handleSubmit} style={{ marginBottom: "2rem" }}>
            <div>
              <label>Nome:</label>
              <input
                type="text"
                value={nome}
                onChange={(e) => setNome(e.target.value)}
                style={{ marginLeft: "0.5rem" }}
              />
            </div>
            <div style={{ marginTop: "1rem" }}>
              <label>Email:</label>
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                style={{ marginLeft: "0.5rem" }}
              />
            </div>
            <button
              type="submit"
              style={{
                marginTop: "1rem",
                padding: "0.5rem 1rem",
                background: "blue",
                color: "white",
                border: "none",
                borderRadius: "5px",
                cursor: "pointer",
              }}
            >
              Cadastrar
            </button>
          </form>

          {/* Lista de clientes */}
          <h2>Clientes Cadastrados</h2>
          {clientes.length === 0 ? (
            <p>Nenhum cliente cadastrado ainda.</p>
          ) : (
            <ul>
              {clientes.map((c, index) => (
                <li key={index}>
                  {c.nome} - {c.email}
                </li>
              ))}
            </ul>
          )}
        </main>
      </div>
    </>
  );
}
