name: Deploy Next.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Pega o código do repositório
      - name: Checkout código
        uses: actions/checkout@v3

      # 2. Configura o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      # 3. Instala as dependências
      - name: Install dependencies
        run: npm ci

      # 4. Rodar ESLint
      - name: Lint
        run: npm run lint

      # 5. Rodar testes
      - name: Run tests
        run: npm run test -- --run --passWithNoTests
      # 6. Build Next.js
      - name: Build Next.js
        run: npm run build

      # 7. (Opcional) Export estático
      - name: Export Next.js
        run: npm run export
