on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18  # ou a versão que você usa localmente

      - name: Install dependencies
        run: npm ci  # usa package-lock.json para garantir versões exatas

      - name: Run tests
        run: npm run test -- --watch=false
        env:
          NODE_OPTIONS: "--experimental-vm-modules" # Necessário para Vitest rodar ESM no CI

      - name: Build Next.js
        run: npm run build
